// === SERVICE WORKER ===
// Makes the app work with no network, which is the whole point of installing it to a
// home screen. The precache list and build id below are generated by tools/build.js,
// so they cannot drift from what index.html actually loads.
//
// In the repository these are placeholder strings; the deployed copy has them filled
// in. That means a service worker served straight from a dev checkout caches nothing
// and simply passes everything through, which is the right behaviour while editing.

const BUILD_ID = '__BUILD_ID__';
const PRECACHE = '__PRECACHE__';
const CACHE_NAME = 'activity-ledger-' + BUILD_ID;
const isBuilt = Array.isArray(PRECACHE);

self.addEventListener('install', event => {
  if (!isBuilt) return;
  event.waitUntil(
    caches.open(CACHE_NAME)
      // addAll is all-or-nothing: one 404 would leave the app with no cache at all
      // and no clue why, so each file is added individually and failures are logged.
      .then(cache => Promise.all(PRECACHE.map(url =>
        cache.add(new Request(url, { cache: 'reload' }))
          .catch(err => console.warn('[sw] could not cache', url, err))
      )))
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys
        .filter(k => k.startsWith('activity-ledger-') && k !== CACHE_NAME)
        .map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (!isBuilt || req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // API responses are never cached. They report live state — whether the deployment
  // has its credentials, whether this browser is connected — and a cached answer is
  // not a stale convenience but a wrong one that outlives the thing it described.
  if (url.pathname.startsWith('/api/')) return;

  // Navigations go to the network first so a deploy is picked up on the next visit,
  // falling back to the cached shell when offline. Everything else is served from
  // cache first for speed, with a quiet background refresh.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req)
        .then(res => {
          const copy = res.clone();
          caches.open(CACHE_NAME).then(c => c.put(req, copy)).catch(() => {});
          return res;
        })
        .catch(() => caches.match(req).then(hit => hit || caches.match('./index.html')))
    );
    return;
  }

  event.respondWith(
    caches.match(req).then(hit => {
      const network = fetch(req)
        .then(res => {
          if (res && res.ok) {
            const copy = res.clone();
            caches.open(CACHE_NAME).then(c => c.put(req, copy)).catch(() => {});
          }
          return res;
        })
        .catch(err => { if (!hit) throw err; return hit; });
      return hit || network;
    })
  );
});

// The page asks for this when the user accepts an update, so the new worker takes
// over immediately instead of waiting for every tab to close.
self.addEventListener('message', event => {
  if (event.data === 'skip-waiting') self.skipWaiting();
});
